name: Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    code:
        name: Test Code
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up node ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Install Dependecies
              uses: bahmutov/npm-install@v1

            - name: Install React
              run: npm i -g react react-dom

            - name: Link Dependencies
              run: npm link react && npm link react-dom

            - name: Run Jest
              run: yarn test --coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    test-bun:
        name: Test Bun
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Bun
              uses: actions/setup-bun@v2

            - name: Install React Globaly
              run: bun i -g react react-dom

            - name: Link Dependencies
              run: bun link react react-dom

            - name: Run Jest
              run: bun run test --coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
